### ISSUE TITLE
Error building examples/aon_counters

### ISSUE THREAD

**Issue by jurobystricky** [01org/qmsi#1]
Cannot build example:

make -C examples/aon_counters

I get errors/warnings:

i586-intel-elfiamcu-gcc -DPRINTF_ENABLE -DPUTS_ENABLE -O0 -g -DDEBUG -std=c90 -Wall -Wextra -Werror -Wno-unused-parameter -fmessage-length=0 -I../../include -fno-asynchronous-unwind-tables -I../../build/debug/quark_d2000/libqmsi/include -march=lakemont -mtune=lakemont -miamcu -msoft-float -DSPI_IRQ_MST -I../../soc/quark_d2000/include -I../../board/drivers -c -o debug/quark_d2000/obj/main.o main.c
In file included from ../../build/debug/quark_d2000/libqmsi/include/qm_aon_counters.h:33:0,
                 from main.c:30:
main.c: In function 'main':
main.c:52:13: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
   QM_PRINTF("Always-on Counter value: %lu\n", c_val);
             ^
../../build/debug/quark_d2000/libqmsi/include/qm_common.h:109:31: note: in definition of macro 'QM_PRINTF'
 #define QM_PRINTF(...) printf(**VA_ARGS**)
                               ^
main.c:52:13: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
   QM_PRINTF("Always-on Counter value: %lu\n", c_val);
             ^
../../build/debug/quark_d2000/libqmsi/include/qm_common.h:109:31: note: in definition of macro 'QM_PRINTF'
 #define QM_PRINTF(...) printf(**VA_ARGS**)
                               ^
main.c:75:13: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
   QM_PRINTF("Always-on Periodic Timer value: %lu\n", pt_val);
             ^
../../build/debug/quark_d2000/libqmsi/include/qm_common.h:109:31: note: in definition of macro 'QM_PRINTF'
 #define QM_PRINTF(...) printf(**VA_ARGS**)
                               ^
main.c:75:13: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t {aka unsign int}' [-Werror=format=]
   QM_PRINTF("Always-on Periodic Timer value: %lu\n", pt_val);
             ^
../../build/debug/quark_d2000/libqmsi/include/qm_common.h:109:31: note: in definition of macro 'QM_PRINTF'
 #define QM_PRINTF(...) printf(**VA_ARGS**)
                               ^
cc1: all warnings being treated as errors

**Comment by jurobystricky** [comment]
I should perhaps mention I use this compiler:
gcc version 5.2.1 20150820 (2016055:B:7018c03:G:ca3fb2e:N:e0faeba:P:e1f6701:L:663880a:E:87c5ff6:L:a90e55c:S:df6d1e6)

**Comment by jurobystricky** [comment]
Also examples/gpio will produce:
i586-intel-elfiamcu-gcc -DPRINTF_ENABLE -DPUTS_ENABLE -O0 -g -DDEBUG -std=c90 -Wall -Wextra -Werror -Wno-unused-parameter -fmessage-length=0 -I../../include -fno-asynchronous-unwind-tables -I../../build/debug/quark_d2000/libqmsi/include -march=lakemont -mtune=lakemont -miamcu -msoft-float -DSPI_IRQ_MST -I../../soc/quark_d2000/include -I../../board/drivers -c -o debug/quark_d2000/obj/main.o main.c
In file included from ../../build/debug/quark_d2000/libqmsi/include/qm_gpio.h:33:0,
                 from main.c:30:
main.c: In function 'gpio_example_callback':
main.c:84:12: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
  QM_PRINTF("GPIO callback - status register = 0x%lu\n", status);
            ^
../../build/debug/quark_d2000/libqmsi/include/qm_common.h:109:31: note: in definition of macro 'QM_PRINTF'
 #define QM_PRINTF(...) printf(**VA_ARGS**)
                               ^
main.c:84:12: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'uint32_t {aka unsigned int}' [-Werror=format=]
  QM_PRINTF("GPIO callback - status register = 0x%lu\n", status);
            ^
../../build/debug/quark_d2000/libqmsi/include/qm_common.h:109:31: note: in definition of macro 'QM_PRINTF'
 #define QM_PRINTF(...) printf(**VA_ARGS**)
                               ^
cc1: all warnings being treated as errors

**Comment by jeez** [comment]
Hi @jurobystricky 

This is a known issue, thanks. It is fixed on the next drop that will be pushed here, but for now you can just change the examples from %lu to %u on the printf lines and it will work. If you send a PR, we can merge it here as well since it's unclear when the new drop will be pushed.

thanks!

**Comment by jeez** [comment]
@jurobystricky it should be fixed now on the v1.0.1 release. Can you please have a look and let me know?

**Comment by jurobystricky** [comment]
I did a fresh pull and there is no problem rebuilding the samples.
