### ISSUE TITLE
QM_

### ISSUE THREAD

**Issue by ghenry** [01org/qmsi#7]
Do we, as devs, really have to use QM_UPPERCASE_BLAH for everything? Why?

**Comment by mprinn** [comment]
Hi Gavin,

Depends what kind of dev, for QMSI drivers we use QM_UPPERCASE_BLAH to hopefully avoid any naming clashes.

If you're developing your own application then you aren't required to follow this naming convention.

**Comment by ghenry** [comment]
I was just looking at your hello_world.c demo and was surprised for _PRINTF

Also, where is the best place for env support? This never returns for me:

$ ./bin/openocd -f scripts/board/quark_d2000_onboard.cfg

[2474131.330747] usb 1-6.4: New USB device found, idVendor=0403, idProduct=6014
[2474131.330760] usb 1-6.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[2474131.330766] usb 1-6.4: Product: D2000 MCU Dev Kit
[2474131.330772] usb 1-6.4: Manufacturer: Intel Corporation
[2474131.330777] usb 1-6.4: SerialNumber: 160500676
[2474131.334697] ftdi_sio 1-6.4:1.0: FTDI USB Serial Device converter detected
[2474131.334776] usb 1-6.4: Detected FT232H
[2474131.335596] usb 1-6.4: FTDI USB Serial Device converter now attached to ttyUSB0

Bus 001 Device 094: ID 0403:6014 Future Technology Devices International, Ltd FT232H Single HS USB-UART/FIFO IC

Open On-Chip Debugger 0.8.0-dev-g7845893 (2015-11-26-17:02)
Licensed under GNU GPL v2
For bug reports, read
    http://openocd.sourceforge.net/doc/doxygen/bugs.html
Info : only one transport option; autoselect 'jtag'
adapter speed: 1000 kHz
trst_only separate trst_push_pull
flash_rom
Info : clock speed 1000 kHz
Info : JTAG tap: quark_d2000.cltap tap/device found: 0x0e786013 (mfg: 0x009, part: 0xe786, ver: 0x0)
Enabling lmt core tap
Info : JTAG tap: quark_d2000.lmt enabled

Just sits there......

**Comment by mprinn** [comment]
Hi Gavin,

For support, please see the following two pages:
http://www.intel.com/content/www/us/en/embedded/products/quark/support-and-community.html
https://communities.intel.com/community/tech/microcontrollers

The second is a forum for posting questions.
Regarding OpenOCD, 
as per chapter 17 in the following:
http://www.intel.com/content/www/us/en/embedded/products/quark/mcu/system-studio-getting-started-guide.html

OpenOCD is waiting for you to establish a connection.
See the steps listed for your OS there to proceed.

**Comment by ghenry** [comment]
Thanks.

On 16 May 2016 at 08:40, Malcolm Prinn notifications@github.com wrote:

> Hi Gavin,
> 
> For support, please see the following two pages:
> 
> http://www.intel.com/content/www/us/en/embedded/products/quark/support-and-community.html
> https://communities.intel.com/community/tech/microcontrollers
> 
> The second is a forum for posing questions.
> Regarding OpenOCD,
> as per chapter 17 in the following:
> 
> http://www.intel.com/content/www/us/en/embedded/products/quark/mcu/system-studio-getting-started-guide.html
> 
> OpenOCD is waiting for you to establish a connection.
> See the steps listed for your OS there to proceed.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/01org/qmsi/issues/7#issuecomment-219367346

## 

Kind Regards,

Gavin Henry.
Managing Director.

T +44 (0) 330 44 50 000
D +44 (0) 330 44 55 007
M +44 (0) 7930 323266
F +44 (0) 1224 824887
E ghenry@suretec.co.uk

Open Source. Open Solutions(tm).

http://www.suretecsystems.com/

Suretec Systems is a limited company registered in Scotland. Registered
number: SC258005. Registered office: 24 Cormack Park, Rothienorman,
Inverurie, Aberdeenshire, AB51 8GL.

Subject to disclaimer at http://www.suretecgroup.com/disclaimer.html

Do you know we have our own VoIP provider called SureVoIP? See
http://www.surevoip.co.uk

Did you see our API? http://www.surevoip.co.uk/api
